server:
  port: 9090
spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}