server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/categoria/**,/producto/**
          filters:
            - AuthFilter
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/cliente/**
          filters:
            - AuthFilter
        - id: venta-service
          uri: lb://venta-service
          predicates:
            - Path=/venta/**
          filters:
            - AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**