server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: inventario-service
          uri: lb://inventario-service
          predicates:
            - Path=/categoria/**,/producto/**
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
              - Path=/cliente/**
        - id: venta-service
          uri: lb://venta-service
          predicates:
              - Path=/venta/**